@startuml blockchainV1 

class Blockchain {
  - chain: [{Block}]
}

class Miner {
  - id: Int
  - blockchain : Blockchain
  - mempool : Mempool
  - wallet : Wallet
  + proofOfWork()
}

class Wallet  {
  - blockchain : Blockchain
  - publicKey: String
  - balance : Int
  + sendCoins()
}


class Block{
}

class Transactions {
}

@enduml