@startuml blockchainV1 

class Blockchain {
  - chain: [{Block}]
  + getChain()
}

class Miner {
  - id: Int
  - blockchain : Blockchain
  - mempool : Mempool
  - wallet : Wallet
  + proofOfWork()
}

class Wallet  {
  - blockchain : Blockchain
  - publicKey: String
  - balance : Int
  + sendCoins()
}


class Block{
  - index : Int
  - timeStamp : Int
  - nonce : Int
  - hash : String
  - previousBlockHash : String
  - transactions : [{Transaction}]
  + static createBlock()
  + addTransaction()
}

class Transactions {
  - transactionID : String
  - coinAmount : Int
  - senderPublicKey : String
  - receiverPublicKey : String
  - isConfirmed : boolean
}

class Mempool{
  - pendingTransactions : [{Transaction}]
  + addTransaction()
}

@enduml